[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmd = "cd server/api-gateway && npm ci"

[phases.build]
cmd = "echo 'No build step required'"

[start]
cmd = "cd server/api-gateway && npm start"

[variables]
NODE_ENV = "production"